flags:
  text:
    integer-simple: false
  QuickCheck:
    base4point8: false
  aeson:
    old-locale: true
packages:
- '.'
extra-deps:
- HTTP-4000.2.20
- HUnit-1.2.5.2
- QuickCheck-2.8.1
- StateVar-1.1.0.0
- adjunctions-4.2.1
- aeson-0.9.0.1
- ansi-terminal-0.6.2.1
- appar-0.1.4
- asn1-encoding-0.9.0
- asn1-parse-0.9.1
- asn1-types-0.3.0
- async-2.0.2
- attoparsec-0.13.0.0
- auto-update-0.1.2.1
- base-orphans-0.3.3
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-5
- blaze-builder-0.4.0.1
- blaze-html-0.8.0.2
- blaze-markup-0.7.0.2
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.6.0.0
- case-insensitive-1.2.0.4
- cereal-0.4.1.1
- comonad-4.2.6
- contravariant-1.3.1.1
- cookie-0.4.1.6
- crypto-numbers-0.2.7
- crypto-random-0.0.9
- cryptonite-0.5
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.4.4
- dlist-0.7.1.1
- easy-file-0.2.1
- exceptions-0.8.0.2
- fast-logger-2.3.1
- free-4.12.1
- hashable-1.2.3.2
- hourglass-0.2.9
- hspec-2.1.7
- hspec-core-2.1.7
- hspec-discover-2.1.7
- hspec-expectations-0.6.1.1
- http-date-0.0.6.1
- http-types-0.8.6
- iproute-1.4.0
- kan-extensions-4.2.2
- lens-4.11
- lifted-base-0.2.3.6
- memory-0.7
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- nats-1
- network-2.6.2.0
- network-uri-2.6.0.3
- parallel-3.2.0.6
- parsec-3.1.9
- pem-0.2.2
- prelude-extras-0.4
- primitive-0.6
- profunctors-5.1.1
- quickcheck-io-0.1.1
- random-1.1
- reflection-1.5.2.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resourcet-1.1.5
- scientific-0.3.3.8
- scotty-0.10.1
- securemem-0.1.9
- semigroupoids-5.0.0.2
- semigroups-0.16.2.2
- setenv-0.1.1.3
- simple-sendfile-0.2.21
- stitch-0.3.0.0
- stm-2.4.4
- streaming-commons-0.1.12.1
- stringsearch-0.3.6.6
- syb-0.5.1
- tagged-0.8.0.1
- text-1.2.1.1
- tf-random-0.5
- tls-1.3.1
- transformers-0.4.3.0
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unix-time-0.3.5
- unordered-containers-0.2.5.1
- vault-0.3.0.4
- vector-0.10.12.3
- void-0.7
- wai-3.0.2.3
- wai-extra-3.0.7.1
- wai-logger-2.2.4.1
- warp-3.0.13.1
- word8-0.1.2
- x509-1.6.0
- x509-store-1.6.0
- x509-validation-1.6.0
- zlib-0.6.1.1
- hspec-wai-0.6.3
resolver: ghc-7.8
